### ISSUE TITLE
Struggling to implement in node red 

### ISSUE THREAD

**Issue by ebsa** [joeartsea/node-red-contrib-ftp#3]
Hi there!

I was wondering whether you could maybe add or supply a guide on exactly how to use the node and what to insert where, like a usage file or description? I have been trying to use the node to upload a file to a ftp server but it is either not doing anything or disconnecting me from my own server. I am really struggling with this and really hope you can assist me. I am not entirely sure how to use it. 

It will be much appreciated

**Comment by joeartsea** [comment]
For example.

```
[{"id":"91039113.5ae0b8","type":"debug","z":"e052b363.bcca48","name":"","active":true,"console":"false","complete":"payload","x":494,"y":72,"wires":[]},{"id":"ebf6cb8.83c77b8","type":"inject","z":"e052b363.bcca48","name":"","topic":"","payload":"","payloadType":"none","repeat":"","crontab":"","once":false,"x":114,"y":141,"wires":[["18704d55.fa8d63"]]},{"id":"18704d55.fa8d63","type":"function","z":"e052b363.bcca48","name":"","func":"msg.filename = 'test.csv';\nmsg.localFilename = '/Users/xxx/Desktop/test_remote.csv';\nreturn msg;","outputs":1,"noerr":0,"x":270,"y":141,"wires":[["6f4f3dda.a20a7c"]]},{"id":"6f4f3dda.a20a7c","type":"ftp in","z":"e052b363.bcca48","ftp":"a7676b1a.e9714","operation":"delete","filename":"","localFilename":"","name":"","x":440,"y":143,"wires":[["be82074.47a8878"]]},{"id":"8e30f382.5971f8","type":"inject","z":"e052b363.bcca48","name":"","topic":"","payload":"","payloadType":"none","repeat":"","crontab":"","once":false,"x":108,"y":67,"wires":[["be82074.47a8878"]]},{"id":"be82074.47a8878","type":"ftp in","z":"e052b363.bcca48","ftp":"a7676b1a.e9714","operation":"list","filename":"","localFilename":"","name":"","x":276,"y":68,"wires":[["91039113.5ae0b8"]]},{"id":"a7676b1a.e9714","type":"ftp","z":"","host":"xxx.xxx.xxx.xxx","port":"21","secureOptions":"","user":"username","connTimeout":"","pasvTimeout":"","keepalive":""}]
```

**Comment by JonasMatos1** [comment]
Hi, 

Can you please exemplify how to put and pull data to and from FTP-Server Node? 
I am able to connect to the node, but cannot put any message into it.

Thanks in advance.

**Comment by juggledad** [comment]
@ JonasMatos1 
To GET a file set
msg.filename = path-to-remote-file/remote-file-name
msg.localFilename = path-on-machine-running-NR/new-file-name

To PUT a file set
msg.filename = path-to-remote-file/remote-file-name-to-be-created
msg.localFilename = path-on-machine-running-NR/file-to-be-put

For example, lets say NR is running on machine 'A' and it is running OS X. You want to send (PUT) a file to the server is running NR and machine 'B' is the ftp server. Lets say the file "mydata.txt'  is in the user 'Paul's main folder and you want to put it in the WWW folder on the server, but the ftp user log's into the root folder and WWW is a alias in the root folder and you want to call the file 'myputdata.txt'

In this case you would set 
msg.filename = www/myputdata.txt
msg.localFilename = Users/paul/mydata.txt

Example 2: same as above, but you are getting into NR using a browser on machine 'C'. You can't move a file on machine 'C'. You have to transfer the file to the NR machine ('A') in order to PUT it. If you run the PUT you will put the file from machine 'A' - the NR machine.

Example 3: You want to GET the file from the server but call it 'igotthisfile.txt', then you would use:
msg.filename = www/myputdata.txt
msg.localFilename = Users/paul/igotthisfile.txt

You can set msg.localFilename in a CHANGE node or in a FUNCTION node. I'm planning on creating a request to expose the msg.localFilename in the FTP node itself.

**Comment by joeartsea** [comment]
@juggledad Thank you. I added the Usage section to the README. This issue will be closed.
